# Generated by Django 4.2.5 on 2023-09-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('phoneNumber', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
                ('nationalNumber', models.CharField(default='', max_length=15)),
                ('birthDate', models.DateField()),
                ('isOwner', models.BooleanField()),
            ],
        ),
    ]
