# Generated by Django 4.2.5 on 2023-09-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('farm', 'Farm')], max_length=20)),
                ('phoneNumber', models.CharField(default='', max_length=10)),
                ('rate', models.IntegerField(default=1, max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'public places',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('publicplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gradapplication.publicplace')),
                ('rentType', models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'farms',
            },
            bases=('gradapplication.publicplace',),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('publicplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gradapplication.publicplace')),
                ('numberOfRooms', models.IntegerField(default=1)),
                ('numberOfStars', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'hotels',
            },
            bases=('gradapplication.publicplace',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('publicplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gradapplication.publicplace')),
                ('openTime', models.DateField()),
                ('menuType', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'restaurants',
            },
            bases=('gradapplication.publicplace',),
        ),
    ]
