# Generated by Django 4.2.5 on 2023-09-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0002_amenities_city_governate_publicplace_room_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='name',
        ),
    ]
