# Generated by Django 4.2.5 on 2023-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0002_publicplace_farm_hotel_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('vip_room', 'vip_room'), ('studio', 'studio')], max_length=10)),
                ('price', models.FloatField(default='', max_length=10)),
                ('roomNumber', models.ImageField(default=1, upload_to='')),
                ('type_bed', models.CharField(choices=[('single', 'single'), ('double', 'double')], max_length=10)),
                ('area', models.FloatField(default='', max_length=20)),
                ('numberOfPerson', models.IntegerField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='farm',
            name='rentType',
            field=models.CharField(choices=[('Daily', 'daily'), ('Monthly', 'monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='area',
            field=models.FloatField(default='', max_length=20),
        ),
    ]
