# Generated by Django 4.2.5 on 2023-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0003_room_alter_farm_renttype_alter_publicplace_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNumber',
            field=models.IntegerField(default=1),
        ),
    ]
