# Generated by Django 4.2.5 on 2023-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0003_remove_amenities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
