# Generated by Django 4.2.5 on 2023-09-21 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0004_alter_room_roomnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='', max_length=20)),
                ('checkin', models.DateField(default=datetime.date.today)),
                ('checkout', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
