# Generated by Django 4.2.5 on 2023-09-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
