# Generated by Django 4.2.5 on 2023-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0006_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalNumber',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
