# Generated by Django 4.2.5 on 2023-09-21 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0007_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default='', max_length=20)),
                ('checkin', models.DateTimeField(default=datetime.date.today)),
                ('checkout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
