# Generated by Django 4.2.5 on 2023-09-21 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0008_tablebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
