# Generated by Django 4.2.5 on 2023-09-21 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0010_alter_tablebooking_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='checkin',
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='checkout',
            field=models.DateField(default=datetime.date(2023, 9, 21)),
        ),
    ]
