# Generated by Django 4.2.5 on 2023-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0011_alter_tablebooking_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
