# Generated by Django 4.2.5 on 2023-09-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0015_alter_city_name_alter_gouvernate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicplace',
            name='userFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.user'),
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='numberOfPerson',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='table',
            name='tableNumber',
            field=models.IntegerField(default=1),
        ),
    ]
