# Generated by Django 4.2.5 on 2023-09-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0017_farmbooking_farmfk_farmbooking_userfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='PublicPlaceFK',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotelfk', to='gradapplication.publicplace'),
        ),
    ]
