# Generated by Django 4.2.5 on 2023-09-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0019_farmbooking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gouvernate',
            new_name='Governorate',
        ),
        migrations.RenameField(
            model_name='farmbooking',
            old_name='checkin',
            new_name='checkInDate',
        ),
        migrations.RenameField(
            model_name='farmbooking',
            old_name='checkout',
            new_name='checkoutDate',
        ),
        migrations.RenameField(
            model_name='farmbooking',
            old_name='FarmFK',
            new_name='farmId',
        ),
        migrations.RenameField(
            model_name='farmbooking',
            old_name='userFK',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='publicplace',
            old_name='rate',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='publicplace',
            old_name='userFK',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='type_bed',
            new_name='bedType',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='numberOfPerson',
            new_name='numberOfPeople',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='checkin',
            new_name='checkInDate',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='checkout',
            new_name='checkoutDate',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='checkin',
            new_name='checkInTime',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='checkout',
            new_name='checkoutTime',
        ),
        migrations.RemoveField(
            model_name='farmbooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='PublicPlaceFK',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type_room',
        ),
        migrations.AddField(
            model_name='room',
            name='hotelId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('single', 'single'), ('double', 'double'), ('vipRoom', 'vipRoom'), ('studio', 'studio')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='roomId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roomId', to='gradapplication.room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.user'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='rentType',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menuType',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openTime',
            field=models.TimeField(),
        ),
    ]
