# Generated by Django 4.2.5 on 2023-09-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0020_rename_gouvernate_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='streetId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.street'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='cityId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.city'),
        ),
        migrations.AddField(
            model_name='street',
            name='PublicPlaceId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.publicplace'),
        ),
        migrations.AlterField(
            model_name='farmbooking',
            name='farmId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.farm'),
        ),
    ]
