# Generated by Django 4.2.5 on 2023-09-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0021_city_streetid_governorate_cityid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('farm', 'Farm')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicPlaceId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.publicplace')),
                ('amenityId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.amenities')),
            ],
        ),
    ]
