# Generated by Django 4.2.5 on 2023-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0023_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='ATM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='CcrRental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='FirstAidServices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='airportDropOff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='cleaningServices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='currencyExchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='dryCleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='faxCopyingServices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='freeParking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='laundryServices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenities',
            name='twintyFourHoursFrontDesk',
            field=models.BooleanField(default=False),
        ),
    ]
