# Generated by Django 4.2.5 on 2023-09-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0026_rename_barbeque_amenities_bbq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='crRental',
            new_name='carRental',
        ),
    ]
