# Generated by Django 4.2.5 on 2023-09-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapplication', '0027_rename_crrental_amenities_carrental'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuType', models.CharField(choices=[('Tasting Menu', 'Tasting Menu'), ('Buffet Menu', 'Buffet Menu'), ('Specials Menu', 'Specials Menu'), ('Beverage Menu', 'Beverage Menu'), ('Kids Menu', 'Kids Menu')], max_length=30)),
                ('restaurantId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gradapplication.restaurant')),
            ],
        ),
    ]
